sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t hyesoo/visionnote -f Dockerfile .

script:
  - docker run -e CI=true hyesoo/visionnote npm run test -- --coverage

after_success:
  - echo "Test success!!"

before_deploy:
  - zip -r visionnote .
  - mkdir -p deploy
  - mv visionnote.zip deploy/visionnote.zip

deploy:
  - provider: s3
    bucket: visionnote
    region: ap-northeast-2
    local_dir: deploy
    skip_cleanup: true
    wait_until_deployed: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    on:
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: visionnote
    key: visionnote.zip
    bundle_key: zip
    application: Lightsail-codedeploy-app
    deployment_group: Lightsail-codedeploy-group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      branch: master

notifications:
  email:
    recipients:
      - hyesoo5115@snu.ac.kr